### ISSUE TITLE
Connect requires protocol argument, should be optional

### ISSUE THREAD

**Issue by cyberixae** [cyberixae/dwst#7]
1) Run command "/connect ws://echo.websocket.org/"

what happens: connection fails because no protocol has been defined
what should happen: connection should succeeds because the server supports an empty protocol string

**Comment by cyberixae** [comment]
The connection dialog works as intended, so this bug does not prevent using the application. The user can also make the console command work by adding an extra space to the end. Like "/connect ws://echo.websocket.org/ ".

**Comment by felipekm** [comment]
+! on this
